
matrix:
  include:

    ############ Linux test ############################

    - name: Linux test

      os: linux
      dist: xenial

      language: cpp

      before_install:

        # Install testrunner-68k

        - sudo add-apt-repository 'deb [trusted=yes] https://testrunner-68k-apt.s3-eu-west-1.amazonaws.com stable main'
        - sudo apt-get update
        - sudo apt-get install -y --allow-unauthenticated testrunner-68k

      script:

        # Build code & run tests

        - make test
