
matrix:
  include:

    ############ Linux test ############################

    - name: Linux test

      os: linux
      dist: xenial

      language: cpp

      before_install:

        # Install testrunner-68k

        - echo "deb https://testrunner-68k-apt.s3-eu-west-1.amazonaws.com stable main" | sudo tee /etc/apt/sources.list.d/testrunner-68k.list
        - wget https://testrunner-68k-apt.s3-eu-west-1.amazonaws.com/Release.key -O - | sudo apt-key add -
        - sudo apt-get update
        - sudo apt-get install testrunner-68k

      script:

        # Build code & run tests

        - make test
